### ISSUE TITLE
Basic authentication is broken (straight to 401)

### ISSUE THREAD

**Issue by ltguillaume** [ungoogled-software/ungoogled-chromium-android#104]
Please at least answer all questions marked with * below. Issues without answering these questions will be closed.

**\*Device info (please complete the following information):**
 - Device: Samsung Galaxy S5
 - OS: LineageOS 17.1
 - Arch: arm
 - Version: 94.0.4606.71
 
**\*Is the bug related to extensions?**
No

**\*If not related to extensions, can the bug be reproduced with corresponding Chromium version?**
No

**\*Describe the bug**
When accessing a website that uses HTTP basic authentication, the browser won't ask for a username and password. Instead, it will directly show the 401 error page. Adding the username inside the URI (https://user:pass@location) won't work either.

**\*To Reproduce**
1. Go to any page using basic authentication
2. See 401 warning

**\*Expected behavior**
The browser should show a popup window to fill in credentials, or use the user/pass combination embedded in the URI.

Bromite, for example, does not exhibit this behavior.

**Comment by ltGuillaume** [comment]
- v94.0.4606.71 is the latest via the F-Droid repo, but I've installed .81 now. For http://httpbin.org/basic-auth/foo/bar I get "This page isn't working HTTP ERROR 401" (slightly different from a my own, but both with 401.
- I have no cache of this site, so that's not a factor. Still, I cleared everything, but to no avail.
- Then I wipe all app data (Titanium Backup) and tried again: **this worked**. I reset everything to my preference, one setting at a time, but it didn't make a difference: everything's working now. I guess something in the profile got corrupted (due to an update)? Thanks for the help!

By the way, the F-Droid repos are sometimes pretty far behind: the WebView is still on v92.0.4515.159

**Comment by wchen342** [comment]
> By the way, the F-Droid repos are sometimes pretty far behind: the WebView is still on v92.0.4515.159

The old Webview version is due to some problems with v93 so I only updated the chromium part. Normally F-Droid will be several days later than Github releases because I need to manually update it.
