### ISSUE TITLE
Requesting extensions-support version for Bromite

### ISSUE THREAD

**Issue by wchen342** [ungoogled-software/ungoogled-chromium-android#27]
Created at the request of some user.

**Comment by varbhat** [comment]
Extension support is most requested feature on Bromite. But,developer has explicitly said that he won't support extensions unless it is upstreamed/maintained by other developers.

People are migrating to Ungoogled chromium because of extensions. I honestly feel that ungoogled chromium is less polished than Bromite(google functions removed but it is not hidden).

i think that creating a fork of bromite with extension support would be good thing.

**Comment by wchen342** [comment]
> ungoogled chromium is less polished than Bromite(google functions removed but it is not hidden)

If the functions referred to are the menu items then they will be removed but they won't do anything. Otherwise ungoogled-chromium is itself in stable status. The extension-support version, however, is not considered stable and is still experimental.

Now from Bromite wiki @csagan5 says that he can add extension if some other project is maintaining the patch. Currently I have the separate patches, but I am not sure whether he will consider the quality acceptable to his project, since functionalities are not all working.

It is still possible, however, just to build a version using those patches, since they are appliable almost directly on chromium's source tree. The only thing that is missing is probably just a building script or directions for Bromite, but it should be very similar to that of chromium, which you can find at [https://chromium.googlesource.com/chromium/src/+/master/docs/android_build_instructions.md](https://chromium.googlesource.com/chromium/src/+/master/docs/android_build_instructions.md).

**Comment by cleanerspam** [comment]
Please you( @wchen342 )  make a fork of Bromite with extension support 

I have many features in mind but they don't fulfil the criteria for ungoogled chromium
P.s Ungoogled Chromium Extensions is not a catchy name for an app maybe Chloride ,Iodide ,or some other cool funky name

**Comment by wchen342** [comment]
@cleanerspam First thing I am already short of computational power (#28). Also I should not take part of Bromite and put it under UC because these are two different projects with different goals.

> Ungoogled Chromium Extensions is not a catchy name for an app maybe Chloride ,Iodide ,or some other cool funky name

As long as upstream is still called `ungoogled-chromium` that part of the name will not change. I am open to ideas about the `-extension` part.

**Comment by csagan5** [comment]
> Now from Bromite wiki @csagan5 says that he can add extension if some other project is maintaining the patch. Currently I have the separate patches, but I am not sure whether he will consider the quality acceptable to his project, since functionalities are not all working.

The problem with extensions is that it is not "just" a patch: you need to access the Google extensions servers, or host your own: that would be a major effort and commitment. So I assume most approaches for Chromium forks will just use Google extensions servers (and that we are OK with that); I have not explored this part at all (what are the privacy implications of using Google servers for the extensions), and whether we are even allowed to use them without showing to the users some ToS to accept.

The second problem with the extensions support is: "support". It would create a ton of bug reports and support requests, simply because Chrom* extensions have never run on Android and in some cases they might have bugs due to that. I have unfortunately no time to dedicate to this.



> The only thing that is missing is probably just a building script or directions for Bromite, but it should be very similar to that of chromium, which you can find at https://chromium.googlesource.com/chromium/src/+/master/docs/android_build_instructions.md.

Yes, if you can build Chromium you should not have any problem with Bromite; there is also https://github.com/nikolowry/bromite-builder by @nikolowry

**Comment by cleanerspam** [comment]
> @cleanerspam First thing I am already short of computational power (#28). Also I should not take part of Bromite and put it under UC because these are two different projects with different goals.
> 
> > Ungoogled Chromium Extensions is not a catchy name for an app maybe Chloride ,Iodide ,or some other cool funky name
> 
> As long as upstream is still called `ungoogled-chromium` that part of the name will not change. I am open to ideas about the `-extension` part.

A fork of ungoogled chromium extension with patches from bromite would be better in comparison to Bromite with extension support
This will fullfil need of both types of user those who use Bromite & want extension support and those who need ungoogled chromium extension with Bromite privacy patches  
This new fork will be a superset for all those users  and since it is a fork you can rename it 

But since you are already low on computational power , I guess it is not possible

**Comment by wchen342** [comment]
> So I assume most approaches for Chromium forks will just use Google extensions servers (and that we are OK with that); I have not explored this part at all (what are the privacy implications of using Google servers for the extensions), and whether we are even allowed to use them without showing to the users some ToS to accept.

I think you raised a good point here. I had not considered this before since I made the patches purely out of curiosity about whether it is possible to do. Until someone from Google come and take actions I will just leave it as it is since there are bigger targets out there (e.g. Brave) so it won't happen soon I suppose. But if there *are* actions taken against the extension version then I will not hesitate taking it down.


My suggestion to anyone who wants a Bromite-extension fork is to look into how @nikolowry's builder works and apply additional patches from here onto the existing building process, essentially creating your own version.

**Comment by csagan5** [comment]
> But since you are already low on computational power , I guess it is not possible

This is the most trivial problem compared to maintaining patches for a Chromium browser; see my reply on #28

**Comment by csagan5** [comment]
> But if there _are_ actions taken against the extension version then I will not hesitate taking it down.

It is unlikely, but since the extensions servers *do* track usage, it is something to tell the browser users for fairness.

**Comment by wchen342** [comment]
> it is something to tell the browser users for fairness

Yeah I kind of "assume" users know they are using Google servers since the only way to install extensions is by the web store (unless they load the extensions in developer mode), but I should add a warning to README.

**Comment by cleanerspam** [comment]
> > it is something to tell the browser users for fairness
> 
> Yeah I kind of "assume" users know they are using Google servers since the only way to install extensions is by the web store (unless they load the extensions in developer mode), but I should add a warning to README.

https://www.crx4chrome.com/ allows downloading extesnions in crx format 
It would be nice to allow automatically installing from here instead of regular downloading as file

**Comment by wchen342** [comment]
> https://www.crx4chrome.com/ allows downloading extesnions in crx format

Universal crx installation from downloading is one thing I am trying to solve now (it doesn't work for `crx` downloaded from Github too). However I will not recommand anything directly to users. They shall take their own responsibility for downloading from third-party sites.

**Comment by nikolowry** [comment]
> My suggestion to anyone who wants a Bromite-extension fork is to look into how @nikolowry's builder works and apply additional patches from here onto the existing building process, essentially creating your own version.

The build script was created with these exact scenarios in mind. Looking at the `extensions` branch, one would need to:

- Download all relevant patches from https://github.com/ungoogled-software/ungoogled-chromium-android/tree/extensions/patches/Extensions to a local folder. I've never tested a custom patches directory that included a sub-directory, so it be best to save those patches in a single-flattened directory. There's also no way to define custom patch order in my build script, so it be best to prefix those patches with numbers corresponding to their patch order (e.g `001-`, `002`, etc)
- When building, add the path of the local patches folder to the `-p` or `--patches-dir` flag: `./bromite-builder -p <path-to-custom-patches>` or `./bromite-builder --patches-dir=<patch-to-custom-patches>`. 
- Custom GN flags can be set with the `-g` or `--gn-args` flag: `./bromite-builder -g "enable_extensions=true enable_supervised_users=false"` or `./bromite-builder --gn-args="enable_extensions=true enable_supervised_users=false"`.

So altogether it would look like:
`./bromite-builder -p <path-to-custom-patches> -g "enable_extensions=true enable_supervised_users=false"` or `./bromite-builder --patches-dir="<path-to-custom-patches>" --gn-args="enable_extensions=true enable_supervised_users=false"`

**Comment by csagan5** [comment]
> * There's also no way to define custom patch order in my build script

There is https://github.com/bromite/bromite/blob/master/build/bromite_patches_list.txt so they could also append the filenames there

**Comment by Sujan319** [comment]
Giving extensions support and maintain it ,itself a huge challenge when google does not want you to use extensions on android.brave team  already working since past year,but now they decide to postpone it as there is upstream complications as said by them.So,instead of doing that ,devs should consider about the necessary things of both user &  themselves to the extent they can able to implement.I was finding a browser that is fast,reliable,feature-rich.for that i used brave a lot nearly 8-9 months,then there was some problem.I moved to vivaldi for 5 days.then I came across bromite.and I thought that is the browser i can keep and i'm very happy using it.But still there was a  quest in my mind.finally I install SOUL BROWSER.it is being developed by a korean devloper .he is the fastest to reply on play store also on email if u mail him.And what a browser that is you have everything you want.there is adblock,dark mode,user-agent changer,custom font,very safe privacy policy"no data collection",faster than the fastest  i.e bromite even chrome,built in pdf reader,online video -downloader button,great user interface like samsung browser, full customisation UI and many more.now it is my no.1 go to browser for any task.Most importantly, the dev is very much eager to work on new feature.however,the browser uses googles server that may be a heart-break for one who dont want to use google.

**Comment by wchen342** [comment]
No source cide can be found, has implanted ads, names themselves a company and has a term of service in Korean only, I won't be too excited about this.
It is of course users' freedom to use whatever browser they like but at least present the whole picture instead of using advertising language. Folding the comments.

**Comment by Sujan319** [comment]
Yes i can understand what you want to say.By the way, I dont advertise it as i also mention what its flaw is.At first ,i'm also unable to understand what their privacy policy as that is in korean.So,google translate help me decoding what they want to said in their privacy policy.but again that is translated version ,user might worry about that but you can contact to the dev via email and i'm telling you he is very fast at replying.if anyone DONT WANT TO USE,THEN DONT USE.What i feel ,i express & share with others as i previously did same for brave & bromite.and most of my friends who used chrome ,they moved from chrome and is surfing adfree & tracking free web.@wchen342  it is natural to think my word as advertisment because of the writing style.Sorry for that.
