### ISSUE TITLE
Force Desktop Mode

### ISSUE THREAD

**Issue by Eloston** [ungoogled-software/ungoogled-chromium-android#33]
Continuation of https://github.com/Eloston/ungoogled-chromium/issues/1174

**Comment by DI555** [comment]
btw, it could be taken patch set of uazo from bromite repo!!!
there're not only 'force desktop mode' , but and 'custom ua' for each mode also!!!

**Comment by wchen342** [comment]
For some reason on the websites I tested they seem to decide the format of their site more on screen resolutions rather then user-agent. I can adjust the flag to freeze on desktop UA, but it seems that doesn't always work on screens that is not larger in width.

**Comment by wchen342** [comment]
Added in 81966c5.

**Comment by DI555** [comment]
wow, i didn't know that sites can take info of screen res. ...((
(i stay for that's mostly a personal info... )

could it be possible to inject this 'screen res. ua' option into about:flags part?   ..that would be really helpful for tunning many sites view... could i create another issue for that?

**Comment by wchen342** [comment]
It'd not the website (the server) knows your resolution, but rather a client rendering of css and js.

The new version's force desktop uses a different way so it will always load in desktop resolution.

**Comment by DI555** [comment]
great, i hope i'll finally drop the habbit to pick '3-dotsMenu' and 'DesktopModeView' each time when i start another page !!!

**Comment by DI555** [comment]
and could you please also add 2 options(at least to about:flags) for MobileUA and DesktopUA?
imo, these 2 options are greatly improove tunning for relations with sites ;)
... sometimes sites ask for exactly up from version number, or they work incorrectly when they didn't recognize current UA ...

**Comment by wchen342** [comment]
It can only be a fixed UA since flags cannot have string inputs.

**Comment by DI555** [comment]
hm, i saw flags with strings ;)

**Comment by wchen342** [comment]
I think it is better giving a selection rather than a text field in this case, since UAs are used every time you open a website. Probably you can put in good strings but is can be a problem for others.

**Comment by DI555** [comment]
the selection needs alway to updating..., because of uppearing new types of ua'es..
the selection is hard to collect all possible ua variants...
some sites may ask/waits only for exactly some types of ua...
but the string , imo, gives the maximum of freedom degrees !
and, yes, the string is no need in updating in future unlike selection!

**Comment by wchen342** [comment]
The UA will be the same as used in desktop mode. It is updated with chromium itself.
I think it is better to just use a extension if you need to change UAs constantly. The use case is very specific.

**Comment by DI555** [comment]
imo this rare type of option with better way in hardcoded place ;)
yes, there're many extensions about ua, but the extension will always work a bit 'over' the browser core.., and i say honestly, sometimes ua-extensions didn't work for me((
but, yes, it's a very specific option. but it may solve many incompatibilities in the future!

**Comment by DI555** [comment]
and another way the 'custom ua' options are in some sort, - 'ungoogled' option either! so it is highly in spirit of ungogled-chromium way! ;)

**Comment by wchen342** [comment]
In this case there is no advantage between an extension and browser itself because the website will only see one UA and extensions shall just overwrite it in header. It basically has nothing to do with other browser parts.

If some extension does not work then either the extension needs update or the extension system, but that is a different problem.

> the 'custom ua' options are in some sort, - 'ungoogled' option

I am not convinced on that. UAs of common browsers always have three parts corresponding to Firefox/genko, chromium/blink and  Safari, so there is nothing to ungoogle here.

**Comment by DI555** [comment]
> UAs of common browsers always have three parts corresponding to Firefox/genko, chromium/blink and Safari, so there is nothing to ungoogle here.

it's mosty a kind of freedom. many sites push different types of itself for different ua'es ... 'ungoogled' its a freedom concept , and 'custom ua' it's a freedom in that way either!

**Comment by wchen342** [comment]
I will not get into a debate about things lie the boundaries of freedom here. There is an [upstream discussion](https://github.com/Eloston/ungoogled-chromium/issues/1192) but it was not expanded much, so you may be able to get some attention there.

The problem is not just about the concept. Technically a string field with arbitrary input can also be dangerous if not treated carefully. It can cause security issues and crashes if not configured correctly. I would rather avoid that risk.

**Comment by DI555** [comment]
ok then, just will use an extension sofar ..., risk of crashes much more dangerous thing.

**Comment by csagan5** [comment]
@uazo your patch got famous :)
