### ISSUE TITLE
Finger printing

### ISSUE THREAD

**Issue by NSTAdventure** [ungoogled-software/ungoogled-chromium-android#71]
**Please explain why your feature request fall into the scope of ungoogled-chromium?**
Finger Printing Around Web Can Be Used To Track User Based On My Test Ungoogled Chromium Doesn't Protect Finger Printing (Not Unique)

**Please describe the feature you would like to have**
A Finger Printing Protection

**Describe the solution you'd like**
Block Finger Print Or Make Finger Print Looks Unique In Any Way

**Describe alternatives you've considered**
No Alternative

**Additional context**
Screenshot Of Test Result:
https://ibb.co/whFkZ1W

Learn More About Finger Printing:
https://coveryourtracks.eff.org/learn

Test It By Yourself:
https://firstpartysimulator.net/

**Comment by wchen342** [comment]
This is the fingerprinting I was trying to explain in #70.

Anti-fingerprinting is very hard to do right and takes more efforts than extensions. It takes Tor Proejct mutiple researchers, contributors and years to make Tor Browser. Since there is no clear definition of what level of enhancement `ungoogled-chromium` want to be I cannot guaruntee anything on this right now.

**Comment by NSTAdventure** [comment]
> This is the fingerprinting I was trying to explain in #70.
> 
> Anti-fingerprinting is very hard to do right and takes more efforts than extensions. It takes Tor Proejct mutiple researchers, contributors and years to make Tor Browser. Since there is no clear definition of what level of enhancement `ungoogled-chromium` want to be I cannot guaruntee anything on this right now.

Atleast you do your best for protect finger printing like DDG Does :)

**Comment by wchen342** [comment]
I will not comment on DDG's approach but I want to point out that wrong approach to this problem will actually make browser more prone to fingerprinting. This is a very complicated topic and researches are still ongoing.

If you want to learn more, I suggest reading some blogs from tor project as well as research papers. For example, [this](https://blog.torproject.org/browser-fingerprinting-introduction-and-challenges-ahead) and [this](https://arxiv.org/pdf/1905.01051.pdf).

**Comment by NSTAdventure** [comment]
> I will not comment on DDG's approach

Hey hey child child bro 

I Mean you can take some ddg code to protect finger printing 🤔

**Comment by wchen342** [comment]
I have already explained why it is not good to take random approaches for this problem, and I do not believe DDG is a good solution for it. Please educate yourself on the topic and then get back to the discussion, otherwise I will consider you as being spamming.

**Comment by NSTAdventure** [comment]
> I have already explained why it is not good to take random approaches for this problem, and I do not believe DDG is a good solution for it. Please educate yourself on the topic and then get back to the discussion, otherwise I will consider you as being spamming.

Alright i just give a idea i want this project grow more

**Comment by wchen342** [comment]
> Do not teasing me

That was not my intention so I apologize if you felt that way.

Let me put it this way: the main objective of this project is one and only one: removing Googe dependencies. All other enhancements are optional and secondary.

I did the extension support out of my interest, but it is *already* beyond the scope of `ungoogled-chromium`. Now the anti-fingerprinting is something as big as extension support if not bigger. If I will do it, *I want to do it right instead of taking random patches from other places*. However, that level of effort is beyond what I currently can do, so I *physically* cannot do it.

**Comment by NSTAdventure** [comment]
> > Do not teasing me
> 
> That was not my intention so I apologize if you felt that way.
> 
> Let me put it this way: the main objective of this project is one and only one: removing Googe dependencies. All other enhancements are optional and secondary.
> 
> I did the extension support out of my interest, but it is _already_ beyond the scope of `ungoogled-chromium`. Now the anti-fingerprinting is something as big as extension support if not bigger. If I will do it, _I want to do it right instead of taking random patches from other places_. However, that level of effort is beyond what I currently can do, so I _physically_ cannot do it.

I also want to apologize  if I offended you
