### ISSUE TITLE
Why this browser with 'arm64' is 130 MBs compared to the 75 MBs of Vivaldi and 50 MBs of Kiwi?

### ISSUE THREAD

**Issue by gitman-2021** [ungoogled-software/ungoogled-chromium-android#89]
The title says it all...;-)

Thanking you

**Comment by wchen342** [comment]
If I get things correct kiwi and Vivaldi are both built against `ChromePublic` which is why it is smaller. However the target is deprecated now. See [https://chromium.googlesource.com/chromium/src/+/HEAD/docs/android_build_instructions.md#Multiple-Chrome-Targets](https://chromium.googlesource.com/chromium/src/+/HEAD/docs/android_build_instructions.md#Multiple-Chrome-Targets).

**Comment by gitman-2021** [comment]
> If I get things correct kiwi and Vivaldi are both built against `ChromePublic` which is why it is smaller. However the target is deprecated now. See https://chromium.googlesource.com/chromium/src/+/HEAD/docs/android_build_instructions.md#Multiple-Chrome-Targets.

Thank you very much for such a kind reply...

**Comment by wchen342** [comment]
The main differences are:

The targeting minimal level of SDK are different. For `ChromePublic`, the minimum level is 18 which is Android 4.4, and for `ChromeModernPublic` it is 21 which is Android 5.0. However, by targeting a low sdk level the codes (Java part) need to have some workarounds or out-dated codes in order to run on old devices, which are not ideal and potentially have security implications.

The other main difference is how whether webview library is bundle inside, but for `ChromePublic` and `ChromeModernPublic` webview is not bundle for both. For `MonochromePublic` for example, the apk will be larger because it includes everything inside its apk.

**Comment by gitman-2021** [comment]
> The main differences are:
> 
> The targeting minimal level of SDK are different. For `ChromePublic`, the minimum level is 18 which is Android 4.4, and for `ChromeModernPublic` it is 21 which is Android 5.0. However, by targeting a low sdk level the codes (Java part) need to have some workarounds or out-dated codes in order to run on old devices, which are not ideal and potentially have security implications.
> 
> The other main difference is how whether webview library is bundle inside, but for `ChromePublic` and `ChromeModernPublic` webview is not bundle for both. For `MonochromePublic` for example, the apk will be larger because it includes everything inside its apk.

I have a few more question if you don't mind:

Why choose `trichrome_chrome_bundle`, instead of `ChromeModernPublic`?
And, If `ChromeModernPublic` ship without the webview, then how it does render the webpages?

Thank you...

**Comment by wchen342** [comment]
> Why choose `trichrome_chrome_bundle`, instead of `ChromeModernPublic`?

There are both `Trichrome` and `ChromeModern` in the release page, you can choose which to download.

> If ChromeModernPublic ship without the webview, then how it does render the webpages?

Maybe something like [this](https://www.quora.com/What-is-the-difference-between-a-WebView-and-a-browser) can help you understand the difference between chrome and webview. They are two difference things.

**Comment by gitman-2021** [comment]
> > Why choose `trichrome_chrome_bundle`, instead of `ChromeModernPublic`?
> 
> There are both `Trichrome` and `ChromeModern` in the release page, you can choose which to download.
> 
> > If ChromeModernPublic ship without the webview, then how it does render the webpages?
> 
> Maybe something like [this](https://www.quora.com/What-is-the-difference-between-a-WebView-and-a-browser) can help you understand the difference between chrome and webview. They are two difference things.

Actually my first question was that, Is there any advantage of choosing `trichrome_chrome_bundle` over `ChromeModernPublic`, and the second one was that, even if  i disable the `Android System Webview`, the `ChromeModernPublic` does not get disturbed, how?

**Comment by wchen342** [comment]
> Is there any advantage of choosing trichrome_chrome_bundle over ChromeModernPublic?

trichrome targets API 29 and above so it is optimized for those systems.

> Even if i disable the Android System Webview, the ChromeModernPublic does not get disturbed, how?

Because they are two different apps and have different apks.

**Comment by gitman-2021** [comment]
> > Is there any advantage of choosing trichrome_chrome_bundle over ChromeModernPublic?
> 
> trichrome targets API 29 and above so it is optimized for those systems.
> 
> > Even if i disable the Android System Webview, the ChromeModernPublic does not get disturbed, how?
> 
> Because they are two different apps and have different apks.

Thank you very much for the information...
